name: Discord Channel Sync
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Update to Discord
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1521388866387312792/4tVN2Qbt9Aefh4fmz46syFGZ3dhlJiH96KcUzw2evgkF1K6f_kR70Y1YI7jlokg5VqN9
        run: |
          AUTHOR="${{ github.actor }}"
          MESSAGE="${{ github.event.head_commit.message }}"
          URL="${{ github.event.head_commit.url }}"
          
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"🚀 **Live Update!** $AUTHOR just pushed new code to GG Loop.\\n\\n**Changes:** $MESSAGE\\n[View the code update]($URL)\"}" \
               $DISCORD_WEBHOOK
